# Site settings
title: Hacklike Engine Xtended
email: libhex-engine@gmail.com
description: Hacklike Engine Xtended is a roguelike development library
  written in Objective-C++, and designed to be as portable as possible.
  It is easy to use, and implements many features which are required by
  any self-respecting roguelike.
baseurl: "/libhex" # the subpath of your site, e.g. /blog/
url: "http://cmura81.github.io" # the base hostname & protocol for your site
github_username:  cmura81

# Build settings
markdown: kramdown
